const TermsAndCondition = () => {
  return (
    <div className="min-h-screen bg-gray-50 dark:bg-black ">
      {/* Container */}
      <div className="mx-auto max-w-5xl px-4 py-8">
        {/* Header */}
        <h1 className="mb-6 text-3xl font-bold text-black dark:text-white">
          Terms and Conditions
        </h1>

        <div className="space-y-7 rounded-lg bg-white p-6 dark:bg-black dark:text-white shadow-lg dark:shadow-white shadow-black">
          {/* Intro */}
          <p className="text-lg leading-relaxed font-extrabold">
            Bella Vita Organic’s <strong>Terms of Use</strong>
          </p>

          <p className="text-sm lg:text-lg leading-relaxed">
            This document is an electronic record in terms of Information
            Technology Act, 2000 and rules framed there under as applicable and
            the amended provisions relating to electronic records in various
            statutes in force as amended by the Information Technology Act,
            2000. This electronic record is generated by a computer system and
            does not require any physical or digital signatures. This document
            is published in accordance with the provisions of Rule 3 (1) of the
            Information Technology (Intermediaries guidelines) Rules, 2011 that
            require publishing the rules and regulations, privacy policy and
            Terms of Use for access or usage of www.bellavitaorganic.com
            website. Bella Vita Organic and Herbal Salon (hereinafter referred
            as Bella Vita Organic) is the owner of the domain name
            www.bellavitaorganic.com
          </p>

          {/* Section */}
          <Section title="USER AGREEMENT">
            <p className="text-sm lg:text-lg leading-relaxed">
              PLEASE READ THIS TERMS OF SERVICE AGREEMENT CAREFULLY. BY USING
              THIS WEBSITE OR ORDERING PRODUCTS FROM THIS WEBSITE YOU AGREE TO
              BE BOUND BY ALL THE TERMS AND CONDITIONS OF THIS AGREEMENT. This
              Terms of Service Agreement (the Agreement) governs your use of
              this website, www.bellavitaorganic.com Bella Vita Organic offers
              products for purchase on this Website, or your purchase of
              products available on this Website. This Agreement includes, and
              incorporates by this reference, the policies and guidelines
              referenced below. Bella Vita Organic reserves the right to change
              or revise the terms and conditions of this Agreement at any time
              by posting any changes or a revised terms of the agreement on this
              Website. Any change or revision in this agreement will be
              reflected with date of change or revision on the top of this
              agreement. The changed or revised Agreement shall be effective
              immediately after it is posted on this Website. Your use of the
              Website or the services available on the website following posting
              any such changes or of a revised Agreement will constitute your
              acceptance of any such changes or revisions. Bella Vita Organic
              encourages you to review these terms of user Agreement whenever
              you visit the Website to make sure that you understand the terms
              and conditions governing use of the Website. This Agreement does
              not alter in any way the terms or conditions of any other written
              agreement you may have with Bella Vita Organic for other products
              or services. If you do not agree to this Agreement (including any
              referenced policies or guidelines), please immediately terminate
              your use of the Website which includes the services available on
              the same. By implicitly or expressly accepting these Terms of Use,
              You also accept and agree to be bound by Bella Vita Organic’s
              Policies (including but not limited to Privacy Policy) as amended
              from time to time. If you would like to print this Agreement,
              please click the print button on your browser toolbar.
            </p>

            <p>
              Bella Vita Organic reserves the right to change or revise these
              terms at any time by posting updates on the website. Continued use
              of the website constitutes acceptance of the updated terms.
            </p>
          </Section>

          {/* Disclaimers */}
          <Section title="IMPORTANT DISCLAIMERS">
            <ul className="list-disc space-y-2 pl-5">
              <p className="text-sm lg:text-lg leading-relaxed">
                The following disclaimers are essential for determining any
                relationship between You and the Bella Vita Organic for your use
                of any services on the website :
              </p>
              <li className="text-md leading-relaxed">
                Bella Vita Organic, its associates, affiliates and service
                providers and technology partners make no representations or
                Warranties about the accuracy, reliability, completeness, and/or
                timelines of any content, information, software, text, graphics,
                links or communications provided on or through the use of the
                Website or that the operation of the Website will be error free
                and/or uninterrupted.
              </li>
              <li className="text-md leading-relaxed">
                You understand, agree and acknowledge that Bella Vita Organic
                uses third party services providers to store and process your
                personal information and other information which you provide to
                the Bella Vita Organic (as more specifically identified in the
                Privacy Policy) and such third parties may store and process
                your personal information in a country or state which may not
                have jurisdiction over You and / or such country or state may
                not have any data protection or data privacy laws or such
                country’s or state’s data protection or data privacy laws may
                not be as strong as the country or state having jurisdiction
                over You or over the Bella Vita Organic. You agree and
                understand that Bella Vita Organic provides no guarantee,
                warranty or assurance that such third party service providers
                will protect Your personal information and Bella Vita Organic
                shall not be liable for any actions, commission, omission,
                misconduct, fraud or negligence (whether in contract or tort or
                under public policy) of these third parties.
              </li>
              <li className="text-md  leading-relaxed">
                You understand, agree and acknowledge that Bella Vita Organic
                will not be liable for any claim of recovery of damages,
                payments, repayments or any monetary claims for banking fraud or
                negligence or damages arising of financial losses, mental agony
                or harassment or whatsoever kind of action in tort or public
                policy or otherwise on account of leakage of any of your
                information including bank details, card details or any other
                delicate personal information in case the website
                www.bellavitaorganic.com is hacked by any third party’s
                intervention through local intervention or international threats
                including through widespread viruses, spams,Trojans, etc. which
                are circumstances beyond the control of Bella Vita Organic and
                for which no fault can be attributable. Bella Vita Organic
                guarantee no security of personal information in such situation
                and none of our privacy policy will be applicable in such
                situation till the time everything in the website is not
                restored to normal.
              </li>
              <p>
                You agree that the aforesaid disclaimers shall be in addition to
                any other disclaimers given in this User Agreement.
              </p>
            </ul>
          </Section>

          {/* Eligibility */}
          <Section title="MEMBERSHIP ELEGIBILITY">
            <p className="text-sm lg:text-lg leading-relaxed">
              In order to use the service of Bella Vita Organic through website
              you may use guest login or you may create your own Bella Vita
              Organic account to use certain Bella Vita Organic Services, and
              you may be required to be logged in to the account and have a
              valid payment method associated with it. You are responsible for
              maintaining the confidentiality of your account and password and
              for restricting access to your account, and you agree to accept
              responsibility for all activities that occur under your account or
              password. To create your Bella Vita Organic account you must be
              eligible to enter into contract under Indian Contract Act, 1872.
              “Incompetent persons” under Indian Contract Act, 1872 are not
              eligible for Bella Vita Organic account. Any minor i.e. a person
              below the age of 18 years can use the website and transact only
              through its legal guardians or Parent. Bella Vita Organic reserves
              the right to terminate your account / refuse to provide its
              services if it is discovered the person using the website and
              making transaction is an “Incompetent person” under Indian
              Contract Act, 1872 who cannot enter into Contract. Any person who
              create account with Bella Vita Organic will be called/referred to
              as Registered User.
            </p>
          </Section>

          {/* Account */}
          <Section title="YOUR ACCOUNT & REGISTRATION OBLIGATIONS">
            <p className="text-sm lg:text-lg leading-relaxed">
              If you use the Website as a Registered User, you are responsible
              for maintaining the confidentiality of your User ID and Password.
              You are responsible for all activities that occur under your User
              ID and Password. You agree, inter alia, to provide true, accurate,
              current and complete information about yourself as prompted by
              Website registration form or provided by You as a Visitor. If you
              provide any information that is untrue, inaccurate, not current or
              incomplete or Bella Vita Organic has reasonable grounds to suspect
              that such information is untrue, inaccurate, not current or
              incomplete, or not in accordance with the present terms of use
              agreement, Bella Vita Organic has the right to indefinitely
              suspend or terminate or block access of your membership with the
              Website and refuse to provide you with access to the Website and
              to provide it services.
            </p>
          </Section>

          <Section title="ELECTRONIC COMMUNICATIONS">
            <p className="text-sm lg:text-lg leading-relaxed">
              When You use the Website or send emails or other data, information
              or communication to us, You agree and understand that You are
              communicating with us through electronic records and You consent
              to receive communications via electronic records from us
              periodically and as and when required. We may communicate with you
              by email or by any other mode of communication, electronic or
              otherwise. You can unsubscribe to any such emails or newsletters
              when there is an option available to you as per the terms
              mentioned in the privacy policy.
            </p>
          </Section>

          {/* Products */}
          <Section title="USE OF PRODUCTS AND SERVICES">
            <p className="text-sm lg:text-lg leading-relaxed">
              The products and services provided by Bella Vita Organic on this
              website are for personal use only. Selling or reselling of
              products and services obtained through Bella Vita Organic website
              is completely prohibited and Bella Vita Organic reserves its right
              to take appropriate legal action in adverse situation. Please note
              that we can call our customers and use their email id for calling
              purposes regarding order and tracking queries and for marketing
              campaigns. Our products are non-returnable due to hygiene and
              personal care nature of the product. However, in the unlikely
              event of damaged, defective or different item delivered to you, or
              regarding the delivery kindly contact us in 24 hrs.
            </p>
          </Section>

          <Section title="FEES AND SERVICES">
            <p className="text-sm lg:text-lg leading-relaxed">
              Membership on this website is free. Bella Vita Organic does not
              charge for browsing and purchasing the product from this website
              except for the sale price of the product, applicable taxes as per
              the laws of India as well as the delivery charges wherever they
              are applicable. If you purchase any product from Bella Vita
              Organic then you are obligatory to make its payment of charges as
              per Bella Vita Organic payment policies. If you do not make
              payment or refuse to make payment of charges after purchasing
              product or services from Bella Vita Organic then Bella Vita
              Organic reserves the right to annul the order or not to deliver
              the said product or to take measures like issuance of warning,
              temporarily /indefinitely suspend or terminate Your membership of
              the Website and refuse to provide You with access to all current
              and future use of the Website in case of non-payment of fees by
              You to www.bellavitaorganic.com and also reserves the right to
              take legal action which is permissible in law for recovery of the
              payments in case of non- payment of charges.
            </p>
          </Section>

          <Section title="USE OF THE WEBSITE">
            <p className="text-sm lg:text-lg leading-relaxed">
              By using this website You agree, undertake and confirm that your
              use of the Website shall be strictly governed by the following
              binding principles:
              <ul>
                <li className="text-md leading-relaxed">
                  • You are solely responsible for your information.
                </li>
                <li className="text-md leading-relaxed">
                  • You shall not host, display, upload, modify, publish,
                  transmit, update or share any information or share/list(s)
                </li>
                <p className="text-md leading-relaxed">
                  – Belongs to some other person to which You do not have any
                  right to.
                </p>
                <p className="text-md leading-relaxed">
                  – Is grossly harmful, harassing, blasphemous, defamatory,
                  obscene, pornographic, paedophilic, libellous, invasive of
                  another’s privacy, hateful, or racially, ethnically
                  objectionable, disparaging, relating or encouraging money
                  laundering or gambling, or otherwise unlawful in any manner
                  whatever; or unlawfully threatening or unlawfully harassing
                  including but not limited to “indecent representation of
                  women” within the meaning of the Indecent Representation of
                  Women (Prohibition) Act, 1986.
                </p>
                <p className="text-md leading-relaxed">
                  – Harm minors in any way.
                </p>
                <p className="text-md leading-relaxed">
                  – Violates any law for the time being in force.
                </p>
                <p className="text-md leading-relaxed">
                  – Threatens the unity, integrity, defence, security or
                  sovereignty of India, friendly relations with foreign states,
                  or public order or causes incitement to the commission of any
                  cognizable offence or prevents investigation of any offence or
                  is insulting any other nation.
                </p>
                <p className="text-md leading-relaxed">
                  – Violate any right of the Bella Vita Organic or its
                  representatives.
                </p>
                <p className="text-md leading-relaxed">
                  – You will not copy any content of this website which is the
                  proprietary interest of Bella Vita Organic, copying of which
                  may violates Intellectual Property Rights of Bella Vita
                  Organic.
                </p>
                <p className="text-md leading-relaxed">
                  – You will not use the details available on the website to
                  mislead any third person.
                </p>
                <p className="text-md leading-relaxed">
                  – You will not write anything about Bella Vita Organic on any
                  social networking or post any of its content without the
                  permission of Bella Vita Organic.
                </p>
                <p className="text-md leading-relaxed">
                  – You will not engage into infringement of the trade mark of
                  Bella Vita Organic by adopting or using the mark Bella Vita
                  Organic or any mark wherein the mark Bella Vita Organic forms
                  one of the essential feature.
                </p>
              </ul>
            </p>
          </Section>

          {/* Liability */}
          <Section title="LIMITATION OF LIABILITY">
            <p className="text-sm lg:text-lg leading-relaxed">
              In no event Bella Vita Organic be liable for any indirect,
              incidental, special, incidental, consequential, punitive or
              exemplary damages, including but not limited to, damages for loss
              of profits, goodwill, use, data or other intangible losses arising
              out of or in connection with the Website, its services or this
              agreement (however arising, including negligence or under torts or
              under public policy).
            </p>
          </Section>

          <Section title="INDEMNITY">
            <p className="text-sm lg:text-lg leading-relaxed">
              You shall fully indemnify, keep indemnified, defend and hold
              harmless Bella Vita Organic its owners, licensees, subsidiaries,
              affiliates, third-parties and their respective shareholders,
              officers, directors, agents, and employees, from any claim or
              demand, or actions including reasonable attorneys’ fees, made by
              any third party or penalty imposed due to or arising out of your
              breach of this terms of use or any rules and policies contained
              herein, or your violation of any law, rules or regulations or the
              rights (including infringement of intellectual property rights) of
              a third party.You also agree to indemnify us for any loss,
              damages, or costs, including reasonable attorneys’ fees, resulting
              from your use of software robots, spiders, crawlers, or similar
              data gathering and extraction tools, or any other action you take
              that imposes an unreasonable burden or load on our infrastructure.
            </p>
          </Section>

          <Section title="DISPUTE RESOLUTIONS">
            <p className="text-sm lg:text-lg leading-relaxed">
              Generally, transactions are conducted smoothly on
              www.bellavitaorganic.com. But in case if any issue arises then at
              www.bellavitaorganic.com , we have a Dispute Resolution process in
              order to resolve disputes amicably between Buyers and Bella Vita
              Organic. A ‘Dispute’ can be defined as a disagreement between a
              Buyer and Bella Vita Organic in connection with a transaction on
              the Website. At www.bellavitaorganic.com you can register your
              grievance at customer care no. or you can write to us at
              shop@bellavitaorganic.com Bella Vita Organic will make its best
              possible effort to to settle the issue amicably before reaching
              out to the complainant and try to amicably resolve the matter
              prior to taking any legal recourse or defending the same.
            </p>
          </Section>

          <Section title="REPORT AN INTELLECTUAL PROPERTY RIGHT VIOLATION">
            <p className="text-sm lg:text-lg leading-relaxed">
              In the event if You believe Your intellectual property rights have
              been violated in any manner through the Website, please write to
              us at shop@bellavitaorganic.com Bella Vita Organic will make it
              best efforts to safeguard your interest. But in any case Bella
              Vita Organic will not be liable for violation of your Intellectual
              Property Right by availability of any third party goods or
              services which are sold on Bella Vita Organic website. Please also
              note that in the event of any claim of the violation of
              intellectual property right raised against Bella Vita Organic,
              then it also reserve its rights to defend the said claims wherever
              Bella Vita Organic deems it appropriate.
            </p>
          </Section>

          {/* Governing Law */}
          <Section title="GOVERNING LAW / JURISICTIONAL ISSUE">
            <p className="text-sm lg:text-lg leading-relaxed">
              This User Agreement and all the rules and policies contained
              herein and any of Your usage of Website and Your dealings with
              Bella Vita Organic shall be governed and construed in accordance
              with the laws of India subject to the exclusive jurisdiction of
              courts at Gurgaon, India.
            </p>
          </Section>

          {/* Grievance */}
          <Section title="Bella Vita Organic – GRIEVANCE OFFICER">
            <p className="text-sm lg:text-lg leading-relaxed">
              This page is published and shall be construed in accordance with
              the provisions of Rule 3(11) of the Information Technology
              (Intermediaries Guidelines) Rules, 2011 (“IT Rules”) that requires
              publishing the name of the Grievance Officer and his/her contact
              details on the website, such that users or any victim who suffers
              as a result of a violation of Rule 3 (outlined in our Privacy
              Policy and Terms of Use) by any other person, can notify their
              complaints to us.
            </p>
            <p className="text-sm lg:text-lg leading-relaxed">
              Further, as per Rule 3(4) of the IT Rules, the Grievance Officer
              shall acknowledge or respond to Your communication of violation of
              Rule 3, by any other person, within 36 (thirty six) hours, and the
              complaints shall be redressed within 1 (one) month from the date
              of receipt of the complaint.
            </p>
            <p className="text-sm lg:text-lg leading-relaxed">
              Accordingly, the Grievance Officer for the purpose of Your
              personal delicate information as governed by the Privacy Policy
              is:
            </p>
            <p>
              <strong>Name:</strong> Aakash Anand
            </p>
            <p>
              <strong>Email:</strong>{" "}
              <a
                href="mailto:shop@bellavitaorganic.com"
                className="text-blue-600 underline"
              >
                shop@bellavitaorganic.com
              </a>
            </p>
          </Section>

          {/* Disclaimer */}
          <Section title="GENERAL">
            <p className="text-sm lg:text-lg leading-relaxed">
              None of the provisions of the User Agreement shall be deemed to
              constitute a partnership or agency between you and Bella Vita
              Organic and you shall have no authority to bind Bella Vita Organic
              in any manner whatsoever.
            </p>
            <p className="text-sm lg:text-lg leading-relaxed">
              If any clause of the Terms of use Agreement shall be deemed
              invalid, void or for any reason unenforceable, such clause shall
              be deemed severable and shall not affect the validity and
              enforceability of the remaining clauses of the User Agreement.
            </p>
            <p className="text-sm lg:text-lg leading-relaxed">
              This Agreement sets forth the entire understanding and agreement
              between You and Bella Vita Organic with respect to the subject
              matter hereof. You cannot assign or otherwise transfer this User
              Agreement, or any rights granted hereunder to any third party.
              shop@bellavitaorganic.commay transfer its rights and obligations
              (also known as “assign”) under this Agreement without Your prior
              express consent, provided that www.bellavitaorganic.com assigns
              the Agreement on the same terms. Bella Vita Organic reserve the
              right, at its sole discretion, to change these Terms and
              Conditions at any time by posting the changes on the website. Any
              changes are effective immediately upon posting to the Site. Your
              continued use of the website thereafter constitutes your agreement
              to all such changed Terms and Conditions.
            </p>
            <p className="text-sm lg:text-lg leading-relaxed">
              Disclaimer: Bella Vita Organic personal care products are based on
              natural and Ayurvedic formulations. Despite the fact that
              tremendous endeavours are made and safeguards are taken to deliver
              the items totally alright for human use, it is conceivable that
              specific fixings may make hypersensitive responses for certain
              people or unfavourably influence people with prior ailments.
              Please make yourself aware of the ingredients and usage
              instructions accompanying each of our products to make sure that
              they are safe for you to use. It will be your sole responsibility
              to take proper precaution/ professional medical/ dermatological
              advice before using any of our personal care products that you may
              be allergic to. You agree that Bella Vita Organic will not be
              responsible or liable for any product related issues, including
              without limitation any allergic reactions to you on account of
              usage of our products. For any buys made through
              www.bellavitaorganic.com, you will entitled to the conditions
              provided in more detail with the product packaging.
            </p>
          </Section>
        </div>
      </div>
    </div>
  );
};

export default TermsAndCondition;

/* Reusable Section Component */
const Section = ({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) => {
  return (
    <div className="space-y-2">
      <h2 className="text-md  lg:text-lg font-semibold dark:text-gray-200 text-gray-900">
        {title}
      </h2>
      <div className="text-xs leading-relaxed dark:text-gray-200 text-gray-700">
        {children}
      </div>
    </div>
  );
};
